create table author (id bigint not null AUTO_INCREMENT, first_name varchar(255), last_name varchar(255), primary key (id));
create table publisher (id bigint not null AUTO_INCREMENT, name varchar(255), address varchar(255), primary key (id));
create table jenre (id bigint not null AUTO_INCREMENT, name varchar(255), primary key (id));
create table book (id bigint generated by default as identity, isbn varchar(255), title varchar(255), jenre_id bigint, publisher_id bigint, primary key (id));
create table book_author (book_id bigint not null, author_id bigint not null, primary key (book_id, author_id));

alter table book add constraint FK_book_jenre foreign key (jenre_id) references jenre;
alter table book add constraint FK_book_publisher foreign key (publisher_id) references publisher;
alter table book_author add constraint FK_book_author_author foreign key (author_id) references author;
alter table book_author add constraint FK_book_author_book foreign key (book_id) references book;